---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.5
  ansible_runner:
    package_pip: ansible-runner
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

images:
  base_image:
    name: quay.io/fedora/fedora:44

additional_build_files:
- src: files/ca.crt
  dest: configs

additional_build_steps:
  prepend_base:
  - RUN dnf install -y python3 python3-pip python3-libdnf5

  prepend_final:
  - RUN whoami
  - RUN cat /etc/os-release
  append_final:
  # - RUN dnf install -y yum-utils
  # - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  # - RUN dnf install -y terraform
  - ADD _build/configs/ca.crt /etc/pki/ca-trust/source/anchors/ca.crt
  - RUN update-ca-trust
  - RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - RUN mv ./kubectl /usr/local/bin
  - RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - RUN chmod +x /usr/local/bin/kubectl
  - RUN chmod +x /usr/local/bin/helm
  # - ENV TF_CLI_ARGS_apply=-parallelism=1 \ TF_CLI_ARGS_destroy=-parallelism=1 \ TF_LOG=INFO
